# === PROFIT LEVELS ===
EXTREME_GREED_PROFIT = 0.18
STANDARD_PROFIT_TAKING = 0.15
BEAR_MARKET_PROFIT = 0.12
SECONDARY_PROFIT_TAKING = 0.30

# === PROFIT TAKING PERCENTAGES ===
EXTREME_GREED_SELL_PCT = 0.25
STANDARD_SELL_PCT = 0.25
BEAR_MARKET_SELL_PCT = 0.30
SECONDARY_SELL_PCT = 0.33

# === MARKET CONDITIONS ===
BTC_DOWNTREND_THRESHOLD = -0.02
MARKET_SCORE_EXTREME_GREED = 0.80
MARKET_BREADTH_BEARISH = 0.25

# === RSI LEVELS ===
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
RSI_EXTREME_OVERSOLD = 20
RSI_EXTREME_OVERBOUGHT = 80

# === VOLUME THRESHOLDS ===
VOLUME_SPIKE_MULTIPLIER = 1.5
VOLUME_MIN_MULTIPLIER = 0.7
VOLUME_EXHAUSTION_MULTIPLIER = 0.6

# === ATR/VOLATILITY ===
MAX_ATR_PERCENTAGE = 0.05
HIGH_VOLATILITY_THRESHOLD = 0.05
VOLATILITY_REDUCTION_MAX = 0.5

# === TIME LIMITS ===
MAX_TRADE_DURATION_HOURS = 48
STOPLOSS_CHECK_INTERVAL = 60

# === DCA SETTINGS ===
DCA_MULTIPLIERS = [1.0, 0.8, 0.6]
MIN_DCA_BUDGET = 1.0

# === MAJOR PAIRS FOR LOGGING ===
DEBUG_PAIRS = ['BTC/USDT:USDT', 'ETH/USDT:USDT', 'SOL/USDT:USDT']

MML_LEVEL_NAMES = [
    "[8/8]P", "[7/8]P", "[6/8]P", "[5/8]P", "[4/8]P", 
    "[3/8]P", "[2/8]P", "[1/8]P", "[0/8]P",
    "[+3/8]P", "[+2/8]P", "[+1/8]P",
    "[-1/8]P", "[-2/8]P", "[-3/8]P"
]