name: Changed Files Pre-Commit Check

on: [push, pull_request]

jobs:
  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - id: changed-files
        name: Check changed files
        uses: dorny/paths-filter@v3
        with:
          token: ${{ github.token }}
          list-files: shell
          filters: |
            repo:
              - added|modified: ['**']
      - run: echo "PY=$(python --version --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Check ALL Files On Branch
        uses: pre-commit/action@v3.0.1
        if: github.event_name != 'pull_request'
      - name: Check Changed Files On PR
        uses: pre-commit/action@v3.0.1
        if: github.event_name == 'pull_request'
        with:
          extra_args: --files ${{ steps.changed-files.outputs.repo_files }}
